### ISSUE TITLE
Add the Satoshi/Byte value to every transaction

### ISSUE THREAD

**Issue by jspri3** [thesmartbit/block-explorer#2]
Reddit request:

> So for an additional feature, you should add the feature I was suggesting in this post.
> Both Tradeblock and Insight have since done it:
> Eg: https://insight.bitpay.com/tx/1bf683c31ebb1017a2873171cb4bf177d92a26309770a95b83cc732c7b27c95c shows the "Fee Rate" (fee per KB). and https://tradeblock.com/blockchain/tx/1bf683c31ebb1017a2873171cb4bf177d92a26309770a95b83cc732c7b27c95c shows the same thing but they call it "Fee/size" and express it in satoshis per byte instead of BTC-per-kb.
> Personally I like bits-per-kb but sat/B might start to grow on me...

**Comment by jspri3** [comment]
bits-per-kb
sat/b

**Comment by jspri3** [comment]
@Chaz27 ?

**Comment by Chaz27** [comment]
@jspri3 Noted, will look at adding that soon.

**Comment by Chaz27** [comment]
@jspri3 "fee_size" now added to api and websocket.

**Comment by jspri3** [comment]
Updates on both mainnet (https://www.smartbit.com.au) and testnet (https://sandbox.smartbit.com.au)
